name: campusbuzz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auth_handler: ^1.0.0
  awesome_dialog: ^3.1.0
  connectivity_plus: ^4.0.2
  custom_alert_dialog_box: ^1.0.2
  dart_eval: ^0.6.0
  easy_rich_text: ^2.0.0
  email_auth: ^1.0.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_core_platform_interface: ^4.8.0
  firebase_database: ^10.2.5
  firebase_messaging: ^14.6.6
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  like_button: ^2.0.5
  readmore: ^2.2.0
  provider: ^6.0.5
  material_design_icons_flutter: ^7.0.7296
  transparent_image: ^2.0.1
  lottie: ^2.6.0
  image_picker: ^1.0.2
  url_launcher: ^6.0.9
  upi_india: ^3.0.1
  video_player: ^2.7.0  
  flutter_local_notifications: ^15.1.0+1
  function_tree: ^0.8.13
  get: ^4.6.5
  google_sign_in: ^6.1.4
  internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^1.0.1
  js: ^0.6.7
  logger: ^2.0.1
  observe_internet_connectivity: ^1.0.2
  overlay_support: ^2.1.0
  invoiceninja: ^0.0.11
  flutter_typeahead: ^4.6.2
  app_settings: ^5.0.0
  cloud_firestore: ^4.9.1
  flutter_riverpod: ^2.4.0
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:

    - assets/images/comp.png
    - assets/images/dj.png
    - assets/images/first.jpg
    - assets/images/forgot.png
    - assets/images/googleeee.png
    - assets/images/third.jpg
    - assets/images/welcome.png
    - images/event1.jpg
    - images/event3.png
    - images/event4.jpg
    - images/event5.webp
    - images/dance.jpg
    - images/music.jpg
    - images/event.jpg
    - assets/images/loggo.png
    - images/b1.jpeg
    - images/b2.jpg
    - images/b3.jpg 
    - images/hacktopia.png
    - images/1real.jpg
    - images/2.png 
    - images/4.jpg
    - images/5.jpg 
    - images/6.jpg 
    - images/vnrvjiet.jpg
    - images/jntu.jpg   
    - images/7.jpg 
    - images/spec.png 
    - images/cheri.jpg
    - images/sahitya.webp
    - images/dance.jpg
    - images/malla.jpg
    - images/bore.jpg
    - images/rishi.jpg
    - images/yt.png



    

